const WORKS = [
  {
    id: "new-vibration",
    title: "New Vibration",
    year: "2026",
    medium: "Acrylic paint on plywood",
    size: "92 × 121 cm",
    image: "assets/new_IMG_5477_2.jpg",
    w: 1600,
    h: 1299,
  },
  {
    id: "good-boy",
    title: "Good Boy",
    year: "2026",
    medium: "Acrylic on paper",
    size: "59 × 42 cm",
    image: "assets/new_IMG_3693.jpg",
    w: 1133,
    h: 1600,
  },
  {
    id: "emo-candy",
    title: "Emo Candy",
    year: "2026",
    medium: "Acrylic and pastel on paper",
    size: "52 × 72 cm, framed",
    image: "assets/new_IMG_5478.jpg",
    w: 1137,
    h: 1600,
  },
  {
    id: "recorded-patterns-of-thought",
    title: "Recorded Patterns of Thought",
    year: "2026",
    medium: "Mixed media on paper",
    size: "52 × 72 cm, framed",
    image: "assets/new_IMG_6153.jpg",
    w: 1600,
    h: 1152,
  },
  {
    id: "untitled-series-1",
    title: "Untitled Series (1)",
    year: "2026",
    medium: "Acrylic on canvas",
    size: "50 × 40 cm",
    image: "assets/new_IMG_3685.jpg",
    w: 1275,
    h: 1600,
  },
  {
    id: "untitled-series-2",
    title: "Untitled Series (2)",
    year: "2026",
    medium: "Acrylic on canvas",
    size: "60 × 60 cm",
    image: "assets/ida.jpg",
    w: 686,
    h: 705,
  },
  {
    id: "bolibompa",
    title: "Bolibompa",
    year: "2026",
    medium: "Mixed media on paper",
    size: "40 × 50 cm, framed",
    image: "assets/new_IMG_5475.jpg",
    w: 1600,
    h: 1419,
  },
  {
    id: "smiley-kissy-silly",
    title: "Smiley, Kissy, Silly",
    year: "2026",
    medium: "Acrylic and spray paint on canvas",
    size: "3 canvases, 160 × 90 cm",
    image: "assets/new_IMG_5470.jpg",
    w: 1600,
    h: 1026,
  },
];
